In [1]:
#Build a dataframe
import pandas as pd
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [5]:
df = pd.DataFrame()
df['color'] = ['blue','red','yellow','green']
df['radius'] = [2,4,3,5]
df #show result

    color  radius
0    blue       2
1     red       4
2  yellow       3
3   green       5

In [6]:
df['diameter'] = df['radius'] * 2
df #output result

    color  radius  diameter
0    blue       2         4
1     red       4         8
2  yellow       3         6
3   green       5        10

In [7]:
#smallest radius
df['radius'].min( )

2

In [9]:
#add up all the diameters
df['diameter'].sum( )

np.int64(28)

In [12]:
#avarage radius
df['radius'].mean( )

np.float64(3.5)

In [ ]:
#Columns as Series
#To reference columns of a dataframe, use square bracket notation:
#df['column_name']

In [13]:
df['color']

0      blue
1       red
2    yellow
3     green
Name: color, dtype: object

In [ ]:
#Rows as Series
#We can also access rows as series. For this we use the iloc[ ] accessor:
#df.iloc[ integer ]

In [16]:
#first row
df.iloc[ 0 ]

color       blue
radius         2
diameter       4
Name: 0, dtype: object

In [17]:
#second row
df.iloc[ 1 ]

color       red
radius        4
diameter      8
Name: 1, dtype: object

In [19]:
#last row
df.iloc[ -1 ]

color       green
radius          5
diameter       10
Name: 3, dtype: object

In [20]:
df.shape

(4, 3)

In [23]:
#number of rows
df.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
df.shape[ 0 ]

4

In [28]:
#number of columns
df.shape[ 1 ]

3