# Pandas

## Three methods are central to dataframe workflows:
     df.eval(): Does calculations.
     df.query(): Finds rows.
     df.groupby(): Builds groups of rows.

# DataFrame.eval
    The eval() method does calculations. 
    It's an efficient way to create new columns from a formula.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame()
df['color'] = ['red','green','yellow','orange','blue']
df['base'] = [15, 30, 8, 12, 22]
df['height'] = [18, 10, 5, 12, 13]
df

    color  base  height
0     red    15      18
1   green    30      10
2  yellow     8       5
3  orange    12      12
4    blue    22      13

In [3]:
#Area = 1/2 × Base × Height
df['area'] = df.eval('0.5 * base * height')
df # display it

    color  base  height   area
0     red    15      18  135.0
1   green    30      10  150.0
2  yellow     8       5   20.0
3  orange    12      12   72.0
4    blue    22      13  143.0

# DataFrame.query()
    The query() method finds rows for a given condition. 
    It's an efficient way to filter a dataframe and get the rows you want.

In [7]:
import pandas as pd

df = pd.DataFrame()
df['month'] = ['January', 'February', 'March', 'April', 'May', 'June',
              'July', 'August', 'September', 'October', 'November', 'December']

df['days'] = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

df['leap_days'] = [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
df

        month  days  leap_days
0     January    31          0
1    February    28          1
2       March    31          0
3       April    30          0
4         May    31          0
5        June    30          0
6        July    31          0
7      August    31          0
8   September    30          0
9     October    31          0
10   November    30          0
11   December    31          0

In [11]:
#find all the months with more than 30 days.
df.query('days > 30')

       month  days  leap_days
0    January    31          0
2      March    31          0
4        May    31          0
6       July    31          0
7     August    31          0
9    October    31          0
11  December    31          0

In [13]:
#find the month with the fewest days.
df.query('days == days.min()')

      month  days  leap_days
1  February    28          1

In [15]:
#less than or equal to
df.query('days <= 30')

        month  days  leap_days
1    February    28          1
3       April    30          0
5        June    30          0
8   September    30          0
10   November    30          0

In [16]:
#equal to
df.query('days == 30')

        month  days  leap_days
3       April    30          0
5        June    30          0
8   September    30          0
10   November    30          0

In [17]:
#not equal to
df.query('days != 30')

       month  days  leap_days
0    January    31          0
1   February    28          1
2      March    31          0
4        May    31          0
6       July    31          0
7     August    31          0
9    October    31          0
11  December    31          0

##### Matching a string

In [20]:
df.query('month == "July"')

  month  days  leap_days
6  July    31          0

##### Matching a list

In [22]:
df.query('month in ["July","August"]')

    month  days  leap_days
6    July    31          0
7  August    31          0

##### Alphabetical cutoff

In [26]:
df.query('month >= "P"')

       month  days  leap_days
8  September    30          0

##### Either or

In [28]:
df.query('days == 30 or leap_days == 1')

        month  days  leap_days
1    February    28          1
3       April    30          0
5        June    30          0
8   September    30          0
10   November    30          0

In [29]:
df.query('month in ["March", "April", "May"]')

   month  days  leap_days
2  March    31          0
3  April    30          0
4    May    31          0

In [30]:
df.query('days == days.max()')

       month  days  leap_days
0    January    31          0
2      March    31          0
4        May    31          0
6       July    31          0
7     August    31          0
9    October    31          0
11  December    31          0

In [31]:
df.query('days == days.min()')

      month  days  leap_days
1  February    28          1

In [33]:
df.query('days > days.mean()')

       month  days  leap_days
0    January    31          0
2      March    31          0
4        May    31          0
6       July    31          0
7     August    31          0
9    October    31          0
11  December    31          0

# DataFrame.groupby()
    groups rows that share a common value. Once grouped, we can perform aggregation calculations, such as min(), max(), mean() and sum().

In [37]:
df = pd.DataFrame()
df['fruit'] = ['strawberry', 'banana', 'pineapple', 'strawberry', 'strawberry',
              'pineapple', 'banana', 'strawberry', 'strawberry', 'banana']
df['weight'] = [10, 118, 800, 11, 12, 900, 124, 13, 11, 131]
df

        fruit  weight
0  strawberry      10
1      banana     118
2   pineapple     800
3  strawberry      11
4  strawberry      12
5   pineapple     900
6      banana     124
7  strawberry      13
8  strawberry      11
9      banana     131

In [41]:
groups = df.groupby('fruit')
groups #display

In [42]:
groups.size()

fruit
banana        3
pineapple     2
strawberry    5
dtype: int64

In [43]:
groups['weight'].mean()

fruit
banana        124.333333
pineapple     850.000000
strawberry     11.400000
Name: weight, dtype: float64

In [44]:
#turn the index into a column using reset_index(). 
#This will convert the series into a dataframe.
groups = df.groupby('fruit')
series = groups['weight'].mean()
series.reset_index()

        fruit      weight
0      banana  124.333333
1   pineapple  850.000000
2  strawberry   11.400000

In [45]:
#This entire groupby calculation is often done as a single line of code
df.groupby('fruit')['weight'].mean().reset_index()

        fruit      weight
0      banana  124.333333
1   pineapple  850.000000
2  strawberry   11.400000