In [1]:
#Build a dataframe
import pandas as pd
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [2]:
df = pd.DataFrame()
# blank dataframe
# we can add columns
df

Empty DataFrame
Columns: []
Index: []

In [3]:
#add one column
df = pd.DataFrame()
df['day'] = ['Mon', 'Tue', 'Wed']
# we can add more
df

   day
0  Mon
1  Tue
2  Wed

In [4]:
#add two columns
df = pd.DataFrame()
df['day'] = ['Mon', 'Tue', 'Wed']
df['temp'] = [22, 25, 20]
df

   day  temp
0  Mon    22
1  Tue    25
2  Wed    20

In [5]:
df['temp2'] = df['temp'] + 10
df

   day  temp  temp2
0  Mon    22     32
1  Tue    25     35
2  Wed    20     30

In [6]:
#frame from object
obj = {'ones':[1,2], 'tens':[10,20]}
df = pd.DataFrame(obj)
df

   ones  tens
0     1    10
1     2    20

In [7]:
#frame from object
df_copy = pd.DataFrame(df)
df_copy['hundreds'] = [100,200]
df_copy

   ones  tens  hundreds
0     1    10       100
1     2    20       200

In [8]:
#Series
vals = pd.Series([3,5,2,11])
vals

0     3
1     5
2     2
3    11
dtype: int64

In [9]:
#series avarage
vals.mean()

np.float64(5.25)

In [10]:
#series sum
vals.sum()

np.int64(21)

In [11]:
#series min
vals.min()

2

In [12]:
""""
#column as series
df['price']
#column max
df['price'].max()
#column median
df['price'].median()
"""

SyntaxError: unterminated string literal (detected at line 8) (445906583.py, line 8)

In [ ]:
df = pd.DataFrame()
df['color'] = ['blue','red','yellow','green']
df['radius'] = [2,4,3,5]
df #show result

In [ ]:
df['diameter'] = df['radius'] * 2
df #output result

In [ ]:
#smallest radius
df['radius'].min( )

In [ ]:
#add up all the diameters
df['diameter'].sum( )

In [ ]:
#avarage radius
df['radius'].mean( )

In [ ]:
#Columns as Series
#To reference columns of a dataframe, use square bracket notation:
#df['column_name']

In [ ]:
df['color']

In [ ]:
#Rows as Series
#We can also access rows as series. For this we use the iloc[ ] accessor:
#df.iloc[ integer ]

In [ ]:
#first row
df.iloc[ 0 ]

In [ ]:
#second row
df.iloc[ 1 ]

In [ ]:
#last row
df.iloc[ -1 ]

In [ ]:
df.shape

In [ ]:
#number of rows
df.index

In [ ]:
df.shape[ 0 ]

In [ ]:
#number of columns
df.shape[ 1 ]